// <auto-generated />
using System;
using AutostradaAuctions.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutostradaAuctions.Api.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20250913233258_InitialSQLiteCreate")]
    partial class InitialSQLiteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BuyNowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasReserve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReservePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningBidId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WinningBidId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ContactInfo = "",
                            CreatedAt = new DateTime(2025, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBid = 67500m,
                            Description = "High-performance BMW M3 with carbon fiber package, track-ready suspension, and manual transmission for the driving purist.",
                            EndTime = new DateTime(2025, 9, 14, 12, 15, 0, 0, DateTimeKind.Utc),
                            HasReserve = true,
                            ReservePrice = 72000m,
                            SellerId = 2,
                            StartTime = new DateTime(2025, 9, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 65000m,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = "2",
                            Title = "2022 BMW M3 - Track-Ready Performance (ENDING SOON!)",
                            VehicleId = 2,
                            ViewCount = 45,
                            WatchCount = 12
                        },
                        new
                        {
                            Id = 11,
                            ContactInfo = "",
                            CreatedAt = new DateTime(2025, 9, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBid = 78500m,
                            Description = "Experience the future of driving with this pristine Tesla Model S featuring Autopilot, premium interior, and full self-driving capability.",
                            EndTime = new DateTime(2025, 9, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            HasReserve = true,
                            ReservePrice = 85000m,
                            SellerId = 2,
                            StartTime = new DateTime(2025, 9, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 75000m,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 9, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = "2",
                            Title = "2023 Tesla Model S - Premium Electric Sedan",
                            VehicleId = 1,
                            ViewCount = 62,
                            WatchCount = 18
                        },
                        new
                        {
                            Id = 12,
                            ContactInfo = "",
                            CreatedAt = new DateTime(2025, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBid = 98000m,
                            Description = "Stunning luxury sports car with handcrafted AMG engine, premium leather interior, and cutting-edge technology.",
                            EndTime = new DateTime(2025, 9, 14, 18, 0, 0, 0, DateTimeKind.Utc),
                            HasReserve = true,
                            ReservePrice = 105000m,
                            SellerId = 2,
                            StartTime = new DateTime(2025, 9, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 95000m,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = "2",
                            Title = "2023 Mercedes-AMG GT - Luxury Sports Car",
                            VehicleId = 3,
                            ViewCount = 34,
                            WatchCount = 8
                        },
                        new
                        {
                            Id = 13,
                            ContactInfo = "",
                            CreatedAt = new DateTime(2025, 9, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBid = 45000m,
                            Description = "Powerful V8 engine, premium interior, and classic American muscle car styling. Perfect for enthusiasts.",
                            EndTime = new DateTime(2025, 9, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            HasReserve = true,
                            ReservePrice = 52000m,
                            SellerId = 2,
                            StartTime = new DateTime(2025, 9, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 45000m,
                            Status = 1,
                            SubmittedAt = new DateTime(2025, 9, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = "2",
                            Title = "2019 Ford Mustang GT - American Muscle",
                            VehicleId = 1,
                            ViewCount = 5,
                            WatchCount = 2
                        },
                        new
                        {
                            Id = 14,
                            ContactInfo = "",
                            CreatedAt = new DateTime(2025, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrentBid = 185000m,
                            Description = "Ultimate performance machine with twin-turbo flat-six engine and PDK transmission. Track-tested perfection.",
                            EndTime = new DateTime(2025, 9, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            HasReserve = true,
                            ReservePrice = 195000m,
                            SellerId = 1,
                            StartTime = new DateTime(2025, 9, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 180000m,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = "1",
                            Title = "2021 Porsche 911 Turbo S - Track Beast",
                            VehicleId = 1,
                            ViewCount = 89,
                            WatchCount = 25
                        });
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.AuctionNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggerTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId", "IsSent", "TriggerTime");

                    b.ToTable("AuctionNotifications");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinning")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BidderId");

                    b.HasIndex("AuctionId", "Amount");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            City = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@autostrada.com",
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$wiAQrFy99wpavWH3alOxku8emSuSu4hJX6Zd8yOdnJAeXH5qr/bDe",
                            PhoneNumber = "",
                            Role = 3,
                            State = "",
                            Username = "admin123",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            City = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@autostrada.com",
                            FirstName = "Regular",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$wiAQrFy99wpavWH3alOxku8emSuSu4hJX6Zd8yOdnJAeXH5qr/bDe",
                            PhoneNumber = "",
                            Role = 1,
                            State = "",
                            Username = "user123",
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId", "AuctionId")
                        .IsUnique();

                    b.ToTable("UserFavorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuctionId = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuctionId = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Pearl White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pristine Tesla Model S with Autopilot, premium interior, and full self-driving capability.",
                            FuelType = "Electric",
                            ImageUrls = "[]",
                            Make = "Tesla",
                            Mileage = 15000,
                            Model = "Model S",
                            Transmission = "Automatic",
                            VIN = "5YJSA1E20MF000001",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Color = "Alpine White",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-performance BMW M3 with carbon fiber package and track-ready suspension.",
                            FuelType = "Gasoline",
                            ImageUrls = "[]",
                            Make = "BMW",
                            Mileage = 8500,
                            Model = "M3",
                            Transmission = "Manual",
                            VIN = "WBS8M9C59N5000002",
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            Color = "Obsidian Black",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxury sports car with handcrafted AMG engine and premium leather interior.",
                            FuelType = "Gasoline",
                            ImageUrls = "[]",
                            Make = "Mercedes-Benz",
                            Mileage = 5200,
                            Model = "AMG GT",
                            Transmission = "Automatic",
                            VIN = "WDDYK7HA2JA000003",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Auction", b =>
                {
                    b.HasOne("AutostradaAuctions.Api.Models.User", "Seller")
                        .WithMany("CreatedAuctions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutostradaAuctions.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Auctions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutostradaAuctions.Api.Models.Bid", "WinningBid")
                        .WithMany()
                        .HasForeignKey("WinningBidId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Seller");

                    b.Navigation("Vehicle");

                    b.Navigation("WinningBid");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.AuctionNotification", b =>
                {
                    b.HasOne("AutostradaAuctions.Api.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutostradaAuctions.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Bid", b =>
                {
                    b.HasOne("AutostradaAuctions.Api.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutostradaAuctions.Api.Models.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.UserFavorite", b =>
                {
                    b.HasOne("AutostradaAuctions.Api.Models.Auction", "Auction")
                        .WithMany("UserFavorites")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutostradaAuctions.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.User", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("CreatedAuctions");
                });

            modelBuilder.Entity("AutostradaAuctions.Api.Models.Vehicle", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
